### ISSUE TITLE
defaultsDeep cause array configuration to be merged instead of overridden

### ISSUE THREAD

**Issue by chasingmaxwell** [aquifer/aquifer#104]
https://github.com/aquifer/aquifer/blob/dev/lib/project.api.js#L43 uses _.defaultsDeep() to override aquifer.json config with aquifer.local.json. This works well until configuration properties are arrays where it merges the two together keeping array elements from both files. For instance, if you override a run profile from aquifer-run, each command gets run twice. Is there a better way for us to override configuration?

**Comment by patrickocoffeyo** [comment]
@chasingmaxwell I think this has been solved.. can you confirm?

**Comment by chasingmaxwell** [comment]
This was still an issue. It's addressed by https://github.com/aquifer/aquifer/pull/178. This is also now a duplicate of this newer issue #177

**Comment by chasingmaxwell** [comment]
PR was merged.
