### ISSUE TITLE
Environments API

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#106]
Many Drupal projects have more than one environment. In most cases, a project has local developer environments, a canonical development environment, a testing/staging environment, and a live environment. 

On all of these environments, we commonly need to run commands to do certain things that change the Drupal site in some way, like drush commands (updb, rr, fra, cc). It's great if these commands can be collected into sets that are run at different points to accomplish a certain goal. For example, let's say that I am deploying a site to a staging server. I want to run the following commands:

```
aquifer deploy-git
drush @remote rr
drush @remote updb -y
drush @remote master-execute
drush @remote fra -y
drush @remote cc all
```

Instead of having to run these commands individually, I should be able to collect these commands into a set, and run them against an environment, so that this task becomes:

```
aquifer deploy-git
aquifer deploy --env staging
```

Right now, Aquifer has no ability to recognize or run series of commands, and it also has no ability to run a series of commands against a specified environment, except for refresh, which can run against a Drush alias. We could use Drush aliases as a way to specify and run commands against environments, but then that limits us to being able to run only Drush commands.

The first step to making this happen is to introduce an "Environments" API to Aquifer core. This API would allow us to define environments against which commands can be run. The Environments API should allow users to define environments in `aquifer.json`, or perhaps in a different file, `aquifer.envs.json`. Once the environments are defined, users should be able to pass an `--env` flag into any aquifer command, and have that command execute itself and all subsequent commands on the specified environment.

**Comment by chasingmaxwell** [comment]
> Right now, Aquifer has no ability to recognize or run series of commands

@patrickocoffeyo There is [aquifer-run](https://github.com/aquifer/aquifer-run) which has proven very useful for several of my projects. We should at least consult the work done there in building a core run API.
