### ISSUE TITLE
Unit test Aquifer

### ISSUE THREAD

**Issue by infiniteluke** [aquifer/aquifer#111]
Unit tests prevent regressions, make refactoring easier, and give maintainers/developers writing/using Aquifer confidence.

[Mocha](https://mochajs.org/) is super popular, but something lighter weight like [Tape](https://www.npmjs.com/package/tape) could probably do the job.

Here's a discussion about [mocha vs tape](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4).

**Which one should we use?**

Once we decide I can get a PR up that adds it to the toolchain.

**Comment by infiniteluke** [comment]
It would also be a good idea to functional test Aquifer with different node/drush versions. Which is the higher priority? unit vs functional?

**Comment by patrickocoffeyo** [comment]
@infiniteluke I have used mocha, and I really like it, and would prefer to use it on this project! :+1:

**Comment by infiniteluke** [comment]
@patrickocoffeyo What are your thoughts on functional vs unit priorities?

**Comment by patrickocoffeyo** [comment]
@infiniteluke I think we should have both, ideally...

**Comment by infiniteluke** [comment]
@patrickocoffeyo BDD??

`expect(foo).to.be.a('string');`
vs
`assert.typeOf(foo, 'string');`
