### ISSUE TITLE
Delete destination files/directories if they exist

### ISSUE THREAD

**Issue by JeffTomlinson** [aquifer/aquifer#115]
`aquifer build` will error out when symlinking/copying source assets into the build if that asset's destination already exists. For example, when using the download version of Acquia Drupal, it will already contain a placeholder `settings.php` file and `/sites/default/files` directory. `fs.SymlinkSync()` will break in this scenario.

**Comment by patrickocoffeyo** [comment]
This is relevant: https://github.com/aquifer/aquifer/issues/103

**Comment by patrickocoffeyo** [comment]
These issues have been solved with the addition of a highly configurable path map system. @JeffTomlinson amazing work on that, I'm closing this task :)
