### ISSUE TITLE
Unable to Rebuild drupal.make.lock

### ISSUE THREAD

**Issue by milsyobtaf** [aquifer/aquifer#125]
On the 1.0.0 branch, there doesn't appear to be a way to rebuild the `drupal.make.lock` file. I tried the `--refresh-lock` flag, and the older `--reset-lock` and `-r` flags, all of which gave an Unknown Option error. I suppose this might have just gone away? But it broke CircleCI builds for UCD-SS. Is there a way to specify an older version of Aquifer in a `circle.yml` file to avoid this in the future?

**Comment by thebruce** [comment]
@milsyobtaf 
In your package.json at the root of your project you could do something like this:
  "dependencies": {
    "aquifer": "aquifer/aquifer#branchname"
  }

**Comment by thebruce** [comment]
Of course that would then be for the project as a whole, which - I don't know if that's going to be ok or not.

**Comment by milsyobtaf** [comment]
_nod_
Makes sense. Thanks @thebruce!

**Comment by patrickocoffeyo** [comment]
We abandoned the concept of using the drush make lock files entirely, there are some core problems with how drush makes use of the lock file. Instead, we recommend that you explicitly define the version of each dependency in the make file.

**Comment by patrickocoffeyo** [comment]
I'mma close this, we can totally re-open it if there is more discussion to be had! :D
