### ISSUE TITLE
Support multisite Drupal

### ISSUE THREAD

**Issue by IslandUsurper** [aquifer/aquifer#127]
I run some websites that have very similar Drupal installations. They have mostly the same modules enabled, they have the same patches to Drupal and certain modules, but their themes and content are different. We use the same code repo on these sites to keep changes in sync and so we know we only have to make a change in one place. I would like to migrate this project to Aquifer for the usual reasons: focus on developing our custom modules instead of keeping track of everyone else's that we use, scriptable deploy steps, etc. However, neither Drush Make nor Aquifer seem to support putting anything in `sites/` except for `sites/all`.

Fortunately, my use case only needs support for settings files and generated features, so Drush Make support for multisite isn't necessary. But if Aquifer never supports it, I'd have to use something else.

**Comment by chasingmaxwell** [comment]
@IslandUsurper! Welcome to work! Multisite Drupal is definitely something aquifer should support. It seems like this would be a relatively simple change to the build API. We would need to parse different "paths" properties in aquifer.json per site. Is `aquifer build` the only feature that would need to change to support multisite?

Are you sure `drush make` doesn't support multisite? Seems like you could use --no-core and --contrib-destination to make it work. Aquifer would need to support multiple make files, one for each site, but that shouldn't be too difficult.

**Comment by IslandUsurper** [comment]
Ah, I guess `--no-core` and `--contrib-destination` would do what I'm asking for, though I was hoping to have only one make file and let each module specify its own "contrib destination" folder, with the default being `sites/all/{type}`. Then you'd only have to run `drush make` once and be done.

It looks like the `refresh` command and the `drush` and `run` extensions should probably be aware of multisite possibilities. Anything that bootstraps Drupal or reads the settings.php file.

**Comment by chasingmaxwell** [comment]
@IslandUsurper, would it not work to spcecify contrib destination in a single make file? I hadn't thought of that but I don't see why it wouldn't work.

You should check out the `1.0.0` branch of aquifer where there has been a lot of really awesome upgrades recently. One of which is that the refresh API and the run extension have both been deprecated in favor of a core run API. I think this new run API should adequately support multisite (although let me know if that isn't the case).

You can use the 1.0.0 branch of aquifer by cloning the repository with git, checking out the 1.0.0 branch, and running `npm link` in the aquifer repo root. That also will make it easy for you to contribute ;)

**Comment by IslandUsurper** [comment]
Unless I haven't seen the right option in the docs, you can only specify what subdirectory within `sites/all/<type>` your project can go in. Common options being "features" and "contrib". But I don't think you can specify `sites/example.com/<type>` with that option. `--contrib-destination` applies to the whole make file, so you have to use multiple invocations to have multiple values for it.

**Comment by IslandUsurper** [comment]
Oh. According to drush-ops/drush#582, you can put `contrib_destination` at the project level. Would be nice if that was in the docs. So Drush Make does support multisite installations in a single makefile, it's just not obvious.

**Comment by patrickocoffeyo** [comment]
I'm interested in looking into this... I think this could easily be supported :)

**Comment by IslandUsurper** [comment]
Once I got the latest version installed, and realized that aquifer.json had changed (or I had gotten it confused with the config.json you can give to `aquifer create`) I found that I can add all of the folders I need and Aquifer will find and sync them. Between that and Drush's `contrib_destination` parameter, I believe my project is completely supported.

**Comment by fluxsauce** [comment]
@IslandUsurper Cool, glad you got it sorted! Want to contribute some documentation so others can learn how?

**Comment by IslandUsurper** [comment]
Sure, @fluxsauce. Where is the best place it should go? Between the wiki and the docs book, it's hard to tell where the most up-to-date information is.

**Comment by patrickocoffeyo** [comment]
@IslandUsurper We are retiring the repository wiki slowly as we improve the book :) [This repo](https://github.com/aquifer/wiki) holds the book that powers docs.aquifer.io. Feel free to fork and add a section on multisites!
