### ISSUE TITLE
graceful-fs

### ISSUE THREAD

**Issue by tschet** [aquifer/aquifer#132]
> (node:27163) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

I'm trying to use aquifer for a project, but I can't seem to get a working install. I get an error on install, and some version of the message above any time I attempt to use it. I've attempted to update graceful-fs without any difference. 
I'm using a new Macbook if it makes a difference.

**Comment by IslandUsurper** [comment]
Ran into this problem just now. Looks like aquifer is using an old version of fs-extra, which depends on graceful-fs. Updating it to 0.30.0 should help.

**Comment by tschet** [comment]
Changing the fs-extra version to 0.30.0 did fix that issue, but now I've getting 

> TypeError:  this.cli._events.hasOwnProperty is not a function
> at Promise (/Users/username/aquifer/lib/aquifer.api.js:133:33)
>     at Aquifer.parse (/Users/username/aquifer/lib/aquifer.api.js:118:12)
>     at Aquifer.initializeCli.then.then.then (/Users/username/aquifer/bin/aquifer.js:53:18)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
>     at Function.Module.runMain (module.js:577:11)
>     at startup (node.js:160:18)
>     at node.js:445:3

**Comment by ccjjmartin** [comment]
EDIT: Scratch this post.  It wasn't actually working, just appeared to be.  I am encountering similar issues that appear to be related to the version of node we are running.

**Comment by tschet** [comment]
Reverting to Node 5 appears to be working

**Comment by ccjjmartin** [comment]
@tschet Node 5 actually does work.  I was having a separate issue on Node 5 I am about to document.  FYI it appears most people using Aquifer are using Node 5.

**Comment by ccjjmartin** [comment]
Until we get a real fix for Node6:

If node was installed using the download from the node website follow the instructions on this page to remove node:
http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

If node was installed with homebrew:
`brew uninstall node`

To install node5:
`brew tap homebrew/versions`
`brew search node`
`brew install homebrew/versions/node5`

See this for install a different node version: (http://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew)

**Comment by proofoftom** [comment]
See PR #137 regarding `TypeError: this.cli._events.hasOwnProperty is not a function` for Node 6.
