### ISSUE TITLE
Nodegit cannot be found

### ISSUE THREAD

**Issue by ccjjmartin** [aquifer/aquifer#136]
## Background:
- Node Version: v5.11.1
- Aquifer Version: 1.0.0-beta1
## Error:
- When running any command including just printing the version, this error occurs:

```
aquifer -V
Error: Cannot find module '../build/Debug/nodegit.node'
1.0.0-beta1
```
## Possible Fix:
- Upgrade to aquifer 1.0.0 because it doesn't require nodegit
- Run `aquifer extensions-load`
## WIP:
- This issue still exists but doesn't appear to be a blocker

**Comment by chasingmaxwell** [comment]
@ccjjmartin it is aquifer-git 1.0.0 that no longer requires nodegit. aquifer core has never required it. Can you upgrade aquifer-git to 1.0.0 and see if the problem disappears?

**Comment by ccjjmartin** [comment]
In order to update:
Go to aquifer.json
Find extensions and change the following:

"extensions": {
     "aquifer-git": {
-      "source": "aquifer-git",
-      "source": "aquifer/aquifer-git#1.0.0",

**Comment by ccjjmartin** [comment]
This appears to require aquifer to be 1.0.0 also which was not the case on our production servers so I had to hold off on this upgrade.
