### ISSUE TITLE
Drush Aliases

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#16]
As a developer, I would like to run drush commands against all the environments that I may have my application deployed to at any given time:

`drush @my-vagrant-instance cc all`

I would also like to be able to run Aquifer commands against a specific environment, such as `aquifer rebuild`.

`aquifer @my-vagrant-instance rebuild`

I would like Aquifer to automatically maintain drush aliases for each of my Aquifer projects

**Comment by patrickocoffeyo** [comment]
@chasingmaxwell @fluxsauce @mattgrill @JeffTomlinson let's discuss this... how should this problem be solved?

**Comment by fluxsauce** [comment]
Generate a PHP file named `aquifer.aliases.drushrc.php` and copy it to `~/.drush`.

``` php
<?php
// Do not edit; generated automatically by aquifer.
$aliases['pizza'] = array(
  'root' => '/path/to/project',
);
```

If the database credentials are known, then you can include that. The extension system, such as for Vagrant, should be able to add to it.

``` php
<?php
// Do not edit; generated automatically by aquifer.
$aliases['pizza'] = array(
  'uri' => 'http://1.2.3.4',
  'root' => '/path/to/project',
  'remote-host' => '1.2.3.4',
  'remote-user' => 'vagrant',
  'ssh-options' => "-i ~/.vagrant.d/insecure_private_key -l vagrant",
  'db-url' => 'mysql://drupal:drupal@123.456.789.0:3306/drupal',
  'databases' => array(
    'default' => array(
      'default' => array(
        'database' => 'drupal',
        'username' => 'drupal',
        'password' => 'drupal',
        'host' => '123.456.789.0',
        'driver' => 'mysql',
      ),
    ),
  ),
);
```

`drush cc drush` then `drush @aquifer.pizza status` would then work.

**Comment by patrickocoffeyo** [comment]
I think we have effectively solved this issue with the run and environment apis. Closing this for now.
