### ISSUE TITLE
Ensure compatibility with latest Node.js version

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#161]
We need to make sure Aquifer is compatible with the latest version of Node.js, and additionally we should add a note in the README.md file that records the supported version of node for each Aquifer version.

**Comment by generalredneck** [comment]
Steps I went through to verify compatibility:
- ran `aquifer create test`
- ran `aquifer build`
- removed test.
- ran `aquifer create test -d 8`
- ran `aquifer build`
- ran `aquifer --help`
- ran `aquifer extensions`
- ran `aquifer extension-add aquifer-git`
- ran `aquifer extension-add aquifer-coder`
- ran `aquifer extensions-load`
- ran `aquifer envs`
- ran `aquifer env-add local`
- ran `aquifer envs` again
- ran `aquifer env-remove local`
- ran `aquifer run refresh`

I didn't see anything unusual in the operation of aquifer on the Latest Stable Node version 6.5.0

**Comment by patrickocoffeyo** [comment]
@generalredneck That's great news! I did the same, and had no issues. 🎉  I'm going to close this ticket now :)
