### ISSUE TITLE
Project-level Aquifer version autoselection

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#163]
We should extend `aquifer.json` so that it includes a `version` property which specifies the version of Aquifer on which the project depends.

When Aquifer is executed it should use/load the correct version of itself. If no `version` property exists, we should warn the user, and default to using the latest and greatest version of this amazing piece of software.

**Comment by chasingmaxwell** [comment]
My plan for this:
- Put a new method in project.api.js for selecting the proper version
- Abstract the bits from extension.api.js that actually use npm to install node modules in the .aquifer directory into an NPM API (npm.api.js) and use it in the extensions api to do what it's already doing.
- Use this same API in project.api.js to install and use the proper version of aquifer.
- I plan to simply execute the other version of aquifer with the exact same parameters and then short-circuit the original aquifer process.

@patrickocoffeyo, does this match your expectation?

**Comment by chasingmaxwell** [comment]
@patrickocoffeyo see PR #167
