### ISSUE TITLE
Allow some src files to be shared between d7 and d8

### ISSUE THREAD

**Issue by chasingmaxwell** [aquifer/aquifer#179]
Why?

The npm API needs to grab the package.json file from src/d7 or src/d8, but because a project-specific version of aquifer itself can be installed with the npm API, it can be invoked before the project API where the source directory is defined. This causes an error if you have aa aquifer version specified in your aquifer.json file but do not have an `.aquifer` directory.

My proposed solution is that we create a src/both directory to hold files that are identical between the two supported versions of Drupal. At the very least I would like to put package.json in that directory so the npm API can grab it without having to know the project's version of Drupal.

**Comment by JeffTomlinson** [comment]
Makes sense to me. Although I'd recommend naming it `src/all`.

**Comment by chasingmaxwell** [comment]
I had just come to the same conclusion in the PR I'm working on :) Great minds.

**Comment by chasingmaxwell** [comment]
PR: https://github.com/aquifer/aquifer/pull/180
