### ISSUE TITLE
D8 support

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#19]
I am of the opinion that Aquifer should support D8 in v1.0.0. However, there are a number of architectural problems that we need to discuss, document, and solve.
## Should Aquifer support D8 and D7 in one version?

I am of the opinion that we should. Since Aquifer is a global CLI, it would be a pain to have to switch between D7 and D8 Aquifer versions just to work on two different Aquifer projects.
## How should Aquifer be architected so that it can support multiple Drupal versions?

I had an idea on this.
Aquifer is broken into API/Command files that are imported when the CLI is initialized. We could simply create Drupal version folders within `/lib` for APIs that are specific to a version of Drupal.

Kind of like this:

```
/lib/
- version_agnostic_thing.api.js
- /D7
-- d7_specific_thing.api.js
- /D8
-- d8_specific_thing.api.js
```

Alternatively, we could suffix files with a major Drupal version:
- `/lib/build.command.d7.js`
- `/lib/build.command.d8.js`

I'm a fan of keeping D8 code separate from D7 code. While it does open up potential to have very un-DRY code, it saves us from making tons of `if (d8) { } else { if (d7) { } }` conditionals.

I may be completely off on my ideas here, please, let's discuss this in the ticket.

**Comment by patrickocoffeyo** [comment]
For the build system, we can use composer instead of Drush Make for Drupal 8... perhaps we can even use composer with Drupal 7?

http://tim.millwoodonline.co.uk/post/124913346140/drupal-8-composer

**Comment by generalredneck** [comment]
Here is a version that uses Drush Make for now. Composer is a separate feature request. See #117.
