### ISSUE TITLE
Decide on a name for this project

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#20]
I named this project Aquifer because it's like an aquifer for Drupal drops... since it's a scaffolding tool for Drupal... get it? :no_good: 

I personally like the name Aquifer quite a bit. Rolls of the tongue, easy to type, great as a command line. However multiple parties have pointed out that it sounds very similar to "Aquia", which is a very different entity that this project is in no way associated with. This is a good point, and so we should consider re-naming the project to avoid confusion.

So, here are the questions:
- Is Aquifer an OK name for this project, or should we change it?
- If we should change the name, what should we change it too?

I'm willing to do all the migration work if we are changing the name, but the decision should be made sooner rather than later.

**Comment by fluxsauce** [comment]
Too close to Acquia for my tastes. I also try to type `acquifer` a lot, and there's already https://github.com/acquifer which is confusing.

https://www.twdb.texas.gov/groundwater/aquifer/major.asp

Trinity? https://www.twdb.texas.gov/groundwater/aquifer/majors/trinity.asp

https://github.com/buildtrinity

**Comment by chasingmaxwell** [comment]
I also like Aquifer. I didn't immediately think of Acquia when I heard it, but I can see how others did. How about Aqueduct? Is that still too similar? Kind of keeps the same idea of providing a scaffolding that transports Drupal drops, but doesn't sound as similar to Acquia.

**Comment by JeffTomlinson** [comment]
I think it's too close to Acquia. I sometimes found myself typing acquifer when testing.
I like aqueduct but maybe still too close?
arroyo?

**Comment by patrickocoffeyo** [comment]
I like the concept of "scaffolding by transporting Drupal drops". Trinity is a great cli name, I like that, but I'm afraid the meaning may escape most people.

What about well? https://github.com/drupalwell

`well create mysitename`
`well build`
`well deploy-vagrant`
`well cs /modules/custom/me`

**Comment by patrickocoffeyo** [comment]
I've been informed the project is being referenced and discussed publicly. Changing the name right now might harm or at least confuse interested parties, and so, I'm voting that we shelve this issue for now. I understand that cross-brand confusion could potentially become a real problem, but given that this project is already getting attention, I think changing the name at this stage may be more harmful than brand confusion. If in the future cross-brand confusion _does_ become a problem, at that point we'll have the forums necessary to properly announce a name change.

Moving forward, I'd like to come up with a distinctive, recognizable logo for Aquifer. This may help prevent cross-brand confusion.

**Comment by patrickocoffeyo** [comment]
This has been shelved for awhile now. I'm closing this. If we decide to revisit renaming Aquifer in the future, we can use this as a starting point of discussion.
