### ISSUE TITLE
Aquifer Branding

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#25]
Considering [recent conversations](https://github.com/aquifer/aquifer/issues/20) about the possibility of cross-brand confusion (Aquifer vs Acquia), I feel that it's very important to create a distinctive, recognizable set of brand colors, and a logo for Aquifer. 

This branding would be used within the CLI, would become the GH org logo, and would be used in any Aquifer-related landing pages, documentation, presentations, etc.

Does anyone have thoughts or ideas on this?

---

**Branding assets notes**
- Github organization profile picture should be `500 x 500`

**Comment by patrickocoffeyo** [comment]
Also, as a fun note, Aquifer has a console api that chooses all sorts of colors that make it a bit more grokable in the command line: https://github.com/aquifer/aquifer/blob/master/lib/console.api.js

Perhaps we can implement some brand colors in the cli too? IDK if that's plausible, but it would be kinda cool.

**Comment by astanush** [comment]
I've always been a fan of 3D cutaway diagrams. Looking through some [aquifer diagrams](https://www.google.com/search?q=aquifer&rlz=1C5CHFA_enUS503US503&espv=2&biw=1279&bih=1318&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMInaSrwpjexgIVwpWICh1ahQa-), a treatment on this imagery could look cool.

As an experiment, I drew a vector version to see what one of these diagrams would look like without labels or shading.

![acquifer-01](https://cloud.githubusercontent.com/assets/202667/8711986/7c8f9526-2b1c-11e5-899a-59ea3f329786.png)

**Comment by patrickocoffeyo** [comment]
I really like the idea of using a cutaway diagram! Perfect for visually demonstrating the concept of an aquifer.

**Comment by patrickocoffeyo** [comment]
@astanush As we push towards a 1.0 release, would it be possible to continue work on the logo? It would be nice to have a distinguishable visual marker.

**Comment by astanush** [comment]
Could you clarify:

> This branding would be used within the CLI

**Comment by patrickocoffeyo** [comment]
@astanush I was thinking that perhaps we could create an ascii art version of the logo and use it in place of the aquifer ascii art we currently have in the help commands.

**Comment by astanush** [comment]
I still like the diagram treatment above as I think it will offer something more unique than the "water drop" seen in a lot of Drupal-related software/companies.

Do you have thoughts about whether to include "Drupal" as part of the product name in certain cases? Since "aquifer" is an English word, it's not that searchable by itself. But if refer to it as "Aquifer for Drupal" or "Aquifer, your Drupal CLI helper". I'm thinking about this less for the CLI-version or a tagline, just wondering if when you land at https://github.com/aquifer/aquifer or a future landing page, which version might be more effective. Example:

![aquifer-1](https://cloud.githubusercontent.com/assets/202667/10297541/365a352a-6b9a-11e5-821a-b7e46e2eab27.png)

![aquifer-2](https://cloud.githubusercontent.com/assets/202667/10297542/39682e34-6b9a-11e5-8400-ab2dc26a70dc.png)

I haven't seen any other Drupal products do this, but it seems like it is allowed in the trademark guidelines - https://www.drupal.com/trademark (See the "Automatic license or license grant procedure?" section)

> The Drupal trademark is used in a domain name, title of website, title of a seminar, title of a course or title of a **software package that is either exclusively intended to foster the Drupal software**, or also mentions your trademark (or your trade name, name of your company, name of your organization, or name of your association).
> 
> Example uses for which you receive an automatic license:
> 
> a commercial plugin to connect Acme's SQL-server to the Drupal software, called "Acme's SQL plugin for Drupal";

**Comment by astanush** [comment]
Do you have release date you're shooting for? Possible to time the release with BADcamp?

**Comment by patrickocoffeyo** [comment]
@astanush I really like the diagram you provided. I think having "for Drupal" in the branding is a good idea as well, given that the word "Aquifer" doesn't in any way indicate that the project is intended to be used for building Drupal sites.

The project is already live on npmjs.org, but I haven't started talking about it a whole lot yet. While I don't have any speaking dates set to talk about Aquifer, I would like to start generally promoting it at BADCamp, just measuring it's usefulness to others and trying to onboard more contributors.

**Comment by astanush** [comment]
Does the NPM site allow for any branding for our page? If so, do they have discrete fields for artwork? Or if it's more open, are there width restrictions?

I'm looking at https://www.npmjs.com/package/aquifer and see you have the ASCII art there, but wondering if we could add an image there?

**Comment by patrickocoffeyo** [comment]
@astanush I believe we can add images to npmjs pages, provided that the image tag uses a full path to pull in the images. Perhaps we should create a `branding` or `landing` repo in this org to add artwork, and then reference the artwork from there?

**Comment by patrickocoffeyo** [comment]
From the gruntjs npm page:
![screenshot from 2015-10-07 17 09 28](https://cloud.githubusercontent.com/assets/1107871/10352703/7ffbae66-6d16-11e5-9b92-039bfb8573cf.png)

**Comment by astanush** [comment]
Instead of having a repo just for artwork — which won't include very many files — maybe we include the artwork assets as part of the landing page repo? We could even have a subpage there for people to download the source files.

**Comment by patrickocoffeyo** [comment]
@astanush I like it :) I've created an empty repository here: https://github.com/aquifer/landing

**Comment by astanush** [comment]
Maybe name the repo to match the domain, e.g. `aquifer.io`?

**Comment by patrickocoffeyo** [comment]
That makes sense to me. I'll update.

**Comment by patrickocoffeyo** [comment]
Done! https://github.com/aquifer/aquifer.io

**Comment by patrickocoffeyo** [comment]
I just got http://docs.aquifer.io up and working. I'll add a basic landing page soon.

**Comment by astanush** [comment]
EPS, PNG, and SVG artwork placed here:

https://github.com/aquifer/aquifer.io/tree/master/branding
