### ISSUE TITLE
Don't use a forked version of drush-node

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer#59]
```
    "drush-node": "chasingmaxwell/drush-node",
```

I found a bug with double-spaced output that I fixed, then went to apply it to https://github.com/elliotttf/drush-node discovered that the diff was incredibly different.

@patrickocoffeyo is a co-maintainer and we have a positive relationship with @elliotttf so let's get things merged.

**Comment by patrickocoffeyo** [comment]
@chasingmaxwell What is the status of this?

**Comment by chasingmaxwell** [comment]
@patrickocoffeyo We can probably remove the dependency to drush-node all together when we've incorporated a "run" code API into aquifer core as we've discussed.
