### ISSUE TITLE
Move extension config to subproperty

### ISSUE THREAD

**Issue by chasingmaxwell** [aquifer/aquifer#62]
It feels awkward to me that extension configuration is at the same level as `source` in aquifer.json. What if you wanted to use "source" as a configuration property! We should move it to a subproperty: `config`

``` json
...
  "extensions": {
    "extension-name": {
      "source": "some source",
      "config": {
        ...
      }
    }
  }
...
```

**Comment by JeffTomlinson** [comment]
PR: https://github.com/aquifer/aquifer/pull/172/files
