### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jasonruyle** [aquifer/aquifer#73]
Tried installing this for the first time on OSX.
When I run aquifer build it starts running the drush make command.
It then returns the following:

```
Wrote .make file                                                     [ok]
/Users/myname/sites/aquifer/myAquifer/drupal.make.lock
Creating symlinks...
Error: EEXIST, symlink '../../../../themes/custom'
```

When I go into the build directory all my sym links are to ../../../ which would be incorrect.

I've had issues with install path problems in the past, this was related to an issue on D8 at:
https://www.drupal.org/node/2464055#comment-10222741

I could be an edge case, but thought I'd let you know.

**Comment by patrickocoffeyo** [comment]
@jasonruyle Thank you for reporting! I will take a look at this.

**Comment by patrickocoffeyo** [comment]
@jasonruyle How did you create your project? Did you just run `aquifer create projectName`, and then attempted to build and it failed? Also, how did you install Aquifer, through npmjs.org?

**Comment by patrickocoffeyo** [comment]
@JeffTomlinson is going to take a look at this as well. I run Linux on my desktop, so if this issue is specific to OSX I may not be able to reproduce it.

**Comment by fluxsauce** [comment]
Hi @jasonruyle , I've been using Aquifer with OSX, haven't experienced that problem.

For troubleshooting, can you provide your `aquifer.json` and `drupal.make` (redacted as much as you'd like)?

**Comment by JeffTomlinson** [comment]
I'm unable to reproduce as well. Will take another look when we get the info @fluxsauce requested.

**Comment by patrickocoffeyo** [comment]
Shelving this because of inactivity. @jasonruyle Thank you for reporting this, we'll keep it in mind, and if you are able to provide more information, feel free to open this back up or create a new ticket with a detailed report.
