### ISSUE TITLE
aquifer extensions-load warning improvement - prompt to run

### ISSUE THREAD

**Issue by thebruce** [aquifer/aquifer#75]
Great project! I was hoping that we could slightly modify the aquifer extensions-load warning behavior. Currently there is a warning prompt if aquifer doesn't have the correct extensions -- you are then left to run aquifer extensions-load after that.  If aquifer is aware at that point - could it prompt the user - to see if now is a good time to run the extensions load?

Something like: `Hey, I noticed that you need a few aquifer extensions, would you like me to try and fetch those now?`

Or more formal, you know w/e -- point is - it is still an opt in behavior - it just gives the option to the user to go out and get everything before it prints out an error initially.

I imagine if it fails to get those extensions that it could move forward with an error/warning - otherwise - the user has the opportunity to get what they want right off the bat.

**Comment by patrickocoffeyo** [comment]
@thebruce this has mostly been solved in #108, but there still is no prompt. W00t!

**Comment by patrickocoffeyo** [comment]
This has been functionally resolved, although we still require users to run `aquifer extensions-load`, this is a very common practice, and I think we are ok with this behavior.
