### ISSUE TITLE
Alias specific refresh commands?

### ISSUE THREAD

**Issue by chasingmaxwell** [aquifer/aquifer#84]
The use case for this is the master module. Right now the default refreshCommands config includes `master-execute --scope=local`. You would want to change the scope on different environments. Since we can specify aliases with the `-a` option we should also be able to specify commands specific to that alias. I'm thinking the config would look something like this (of course with more commands defined for each alias):

``` json
{
  "refreshCommands": {
    "@local": [
      [
        "master-execute",
        "--scope=local"
      ]
    ],
    "@live": [
      [
        "master-execute",
        "--scope=live"
      ]
    ]
  }
}
```

This would be an API breaking change so I wanted to check with y'all before I started work on it. Any thoughts? If it sounds good I'll create a PR today.

**Comment by chasingmaxwell** [comment]
of course there should also be a default set of commands for the local build without an alias specified. That could just be a "default" key.

**Comment by patrickocoffeyo** [comment]
@chasingmaxwel This makes sense. Would it make more sense to move the refresh command into an extension, and then include it as a default?

**Comment by chasingmaxwell** [comment]
@patrickocoffeyo++ yes! I'll do that now.
