### ISSUE TITLE
Support custom drushrc.php files

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer#85]
You can set Drush defaults in a `drushrc.php` file, which [according to the documentation](https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php) can live in places like `./sites/all/drush/drushrc.php`

Provide a logical default and placeholder.

**Comment by fluxsauce** [comment]
Now it requires that you have a drush configuration. Whoops!

**Comment by infiniteluke** [comment]
The work around for this would be to add `"drush": "drush"` under `"paths"` in your aquifer.local.json file. It will get things building again if you're using the dev branch with your projects.

**Comment by infiniteluke** [comment]
#93 will track the handling of required config
