### ISSUE TITLE
Use Composer instead of Drush Make

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#87]
I think we should use composer instead of drush make to define dependencies and scaffold a drupal site root. thoughts?

**Comment by thebruce** [comment]
@patrickocoffeyo we've been talking about this quite a lot in aquifer slack and at Four Kitchens central. I think this is definitely the way the wind is blowing, and I think moving to this is a great idea.  I've talked about this at some length with @generalredneck and of course you and I have talked about it as well.

Here is a summary of a few of the things we've said:
- We'd like to maintain the build behaviors of aquifer, that is the current structure of the project, that composer will build into a specified build folder with a composer.json file at the root - we could then use the path maps branch you've been working on or w/e, but we _would not_ build the project into the root of the aquifer folder.
- I think it matches the general philosophy of the project to abstract out the build tool part of the build tool api and have implementations for drush make and composer. However we've got several options here:
  - We use simple switch statements with options to choose between the two systems. Good for now - not far thinking - but might be the quickest way to support both that we can iterate on later.
  - We can create a composer branch that only supports composer and deprecates drush make. Maybe this workflow is a dinosaur and we need to bury it with the undead robots from the dawn of time.
  - We can create a build tool api and implementing classes for composer and drush - I like this the best but it will take a bit of time. Especially for me at the moment.
- This next point may be ancillary but working out support for the packagist composer approach (which I think makes the most sense to me based on @generalredneck's experience and discussion - but granted I need to do more reading) and then in doing so have we precluded an approach to composer based builds using composer manager, and are we OK with that.  Maybe that's a separate issue or perhaps it's tied. Looking forward to more discussion.
- The final thing to bring up - and this is definitely outside the concerns of this particular issue but is affected - is how the work we do to move to this build system impacts our most common Drupal host specific situations, pantheon and acquia and their own composer inclusions.

OK - well that's at least a start. Everybody pile in, nicely though!
