### ISSUE TITLE
Aquifer commands fail with wrong exit code if Drush commands fail

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer#90]
![screen shot 2015-11-11 at 3 53 08 pm](https://cloud.githubusercontent.com/assets/976391/11106620/54e2e41a-888c-11e5-9b59-85894acf8852.png)

**Comment by fluxsauce** [comment]
Okay, with some further testing...
- Drush shouldn't have to be installed globally for Aquifer to work. Need to be able to specify a path to a Drush binary.
- Test to see if Drush is available before trying to use it. If it isn't available, bail with an appropriately verbose command describing what's wrong.
- If commands fail, use an exit code.

**Comment by fluxsauce** [comment]
Looks like Aquifer doesn't pay attention to the Drush exit codes in general.

<img width="706" alt="screen shot 2015-11-12 at 11 32 02 pm" src="https://cloud.githubusercontent.com/assets/976391/11141000/b0209e26-8995-11e5-953c-748e33b6decf.png">

<img width="698" alt="screen shot 2015-11-12 at 11 32 09 pm" src="https://cloud.githubusercontent.com/assets/976391/11141001/b02259d2-8995-11e5-8cb6-eafd1f061d60.png">

**Comment by patrickocoffeyo** [comment]
@fluxsauce Looking into this, I think this may be an issue with the `drush-node` wrapper. 

@chasingmaxwell is working on a mechanism to replace drush-node, and all other command wrappers that we currently use. This mechanism will report errors correctly, in fact that's something we should specifically test for. These sort of errors are annoying and unhelpful.

In response to a Drush binary, I think we should, going forward, keep all _core_ dependencies local. We need to be able to use a specific version of drush, and have control over that if we want Aquifer to work well & use Drush at the same time. I'll make some issues around this.

**Comment by chasingmaxwell** [comment]
@fluxsauce @patrickocoffeyo this is an issue with the way aquifer handles extension commands. If there is an error returned by the command, aquifer just logs it. It should log it and exit with non 0 error code. here's the relevant line: https://github.com/aquifer/aquifer/blob/dev/lib/extension.command.js#L165

```
      command.action(function (options) {
        options = options || {};

        extensions[extensionName].run(commandName, options, function (err) {
          if (err) {
            Aquifer.console.log(err, 'error');
          }
        });
      });
```
