### ISSUE TITLE
Make directories, such as files, optional when building

### ISSUE THREAD

**Issue by fluxsauce** [aquifer/aquifer#96]
`aquifer-git` creates an artifact and commits it to a repository, and it works. However, the build process copies the files directory, which is ignored within `aquifer-git` using a `.gitignore`. I noticed because my files directory is ~25GB.

https://github.com/aquifer/aquifer-git/issues/12

**Comment by chasingmaxwell** [comment]
I've created #97 to deal with this. It allows options to be passed to the build API excluding links or adding new links. aquifer-git will use this to exclude the files directory by default.
